apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: frontend
    component: app1
spec:
  replicas: 2
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: frontend
      component: app1
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: app1
    spec:
      containers:
      - name: app1
        image: manikanta1808/app1:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: frontend
    component: app1
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations: # To select the external service provider, in this case it is AWS ALB
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:030796672830:certificate/52e897ad-3839-4918-a7a6-384f52918e56'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: roboshop
spec:
  ingressClassName: alb # Creating Application Load Balancer
  rules:
  - host: "app1.dawsmani.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80

# Ingress is communicating with ingress drivers. Ingress drivers are responsible for creating the load balancer and configuring the load balancer to route the traffic to the service. 

# If errors in creating resources, then check the drivers and events of the ingress resource.